### ISSUE TITLE
Workaround for ReSharper regarding `ShouldNotBeNull()`

### ISSUE THREAD

**Issue by mu88** [fluentassertions/fluentassertions#1074]
Please take a look at this code:
```
var car = new Car();
Assert.IsNotNull(car);
Assert.IsTrue(car.HasEngine);
```

When using ReSharper, it works perfectly fine without any complaints. Now I "translate" the code into...
```
var car = new Car();
car.ShouldNotBeNull();
car.HasEngine.Should().BeTrue();
```
... which makes ReSharper complaining about the last line saying that `car` can be null.

There is a ReSharper issue regarding this topic as well: [Extend support for FluentAssert](https://youtrack.jetbrains.com/issue/RSRP-442740)

Do you see any lightweight workaround that can be included in FluentAssertions without polluting the code base with a dependency to a third-party tool?

**Comment by jnyrup** [comment]
Be aware that the two code snippets are not *always* equivalent.
When wrapping multiple assertions in an `AssertionScope`, the execution of assertions continues even if one of them fails.

The following code hits an `NullReferenceException`.
```c#
Car car = null;

using (new AssertionScope())
{
    car.Should().NotBeNull();
    car.HasEngines.Should().BeTrue();
}
```

**Comment by mu88** [comment]
But was is the value of `Should().NotBeNull()` if not used like that?

**Comment by jnyrup** [comment]
For 
```c#
car.Should().NotBeNull();
```
the return type of `NotBeNull` in this example `AndConstraint<ObjectAssertions>`, which is used to chain multiple assertions.

The return type is independent of whether I'm using an `AssertionScope`.

If I'm *not* using an `AssertionScope` `NotBeNull` terminates the execution of further assertions, and hence `car` will never be `null` if executing `car.HasEngines`.

The problem is that this cannot be used as a compile time invariant, as I can construct an example where is does not hold.

**Comment by mu88** [comment]
Technically, I understand you. But from the perspective of a consuming developer, this should be at least documented. Even within [the documentation](https://fluentassertions.com/tips/#mstest-migration) there is the analogy between `Assert.IsNotNull()` and `Should().NotBeNull()`.

**Comment by jnyrup** [comment]
By default the analogy holds, but consumers are able to override that behavior.
So we can't statically guarantee `car` to *always* be not `null`.
I'm not deep into using these kinds of attributes and whether it would be a misuse to mark `car` as not `null` if `NotBeNull()` does not fail.

Do you think that adding my example above to https://fluentassertions.com/documentation/#assertion-scope would cover the lack of documentation you're seeing?

**Comment by mu88** [comment]
Yes, I would think so. But more importantly, it should be added to the MSTest-Migration, because simply replacing `Assert.IsNotNull()` with `Should().NotBeNull()` now seems wrong to me.

Do you see any alternatives?

**Comment by jnyrup** [comment]
I'm not sure I follow.
Replacing `Assert.IsNotNull()` with `Should().NotBeNull()` will work, i.e. checking whether the subject is `null`.

If that case should be documented for `NotBeNull`, then *all* assertions should have that addendum, as one can construct examples where wrapping two assertions in an `AssertionScope` can throw an unexpected exception.

E.g.
```c#
index.Should().NotBeNegative();
list[index].Should().Be(42);
```

**Comment by dennisdoomen** [comment]
Now I wonder how R# understands that `Assert.IsNotNull` will ensure that `car` can no longer be null. Did they add the Resharper Annotations attributes to the framework? Or does R# have special support for that.

**Comment by mu88** [comment]
@dennisdoomen I really don't know. I've already asked this question in [JetBrains' corresponding Issue](https://youtrack.jetbrains.com/issue/RSRP-442740#focus=streamItem-27-3506960.0-0), but unfortunately got no answer. Since R# has built-in MSTest support, I could imagine a special handling of `Assert.IsNotNull()` within the product,

@jnyrup Let's assume I'm using R# and I have an already existing test that looks like this:
```
var car = new Car();
Assert.IsNotNull(car);
Assert.IsTrue(car.HasEngine);
```
Now I read the documentation of Fluent Assertions and get the idea that I can simply replace it with:
```
var car = new Car();
car.ShouldNotBeNull();
car.HasEngine.Should().BeTrue();
```
Now I'm encountering a R# warning saying that `"car" can be null` in the very last line. So the two versions may don't vary in their behavior during runtime, but they cannot be simply replaced. Imagine an enterprise saying that every code file must not contain any R# warning (like the company I'm working for 😉)... now I've got a problem.

**Comment by dennisdoomen** [comment]
We'll investigate, but it is very well possible using the R# attributes is not enough. 

>  Imagine an enterprise saying that every code file must not contain any R# warning (like the company I'm working for 😉)... now I've got a problem.

I'm working with (and advising) enterprises like this and nobody had every any objections on muting these warnings at the file level. So I don't agree that's such a big deal.

**Comment by mu88** [comment]
Thanks for taking care about this!

**Comment by Evangelink** [comment]
I don't think null pointer warnings in unit tests are such a big deal because it is still caught before any prod.

At the same time, and I might be wrong with it, but I would favor having some False Negatives instead of False Positives here. Most people are probably using the simple scenario and would prefer not to have a FP message from ReSharper. For more advanced users, who will wrap assertions in the `AssertionScope` they would end up with a False Negative (no message from ReSharper).

_just my 2 cents_

**Comment by rikrak** [comment]
For Info (and to prevent me from looking into this a second time :-) ):

ReSharper can decorate external libraries by using _External Annotation_ files[1].  There are a whole load of them shipped with R#.  I found the MSTest annotaions here[2] on my machine.

Unfortunately, I don't think this approach would work for FluentAssertions as it would rely on the `ContractAnnotationAttribute`[3] to indicate an exception would occur on a null value.  The `ContractAnnotationAttribute` can only deal with method parameters when indicating that an exception can occur.  This will work for `Assert.IsNotNull(object value)` as the value being tested is a parameter, but in the case of FluentAssertions, the null value will be on a class property.

For reference there is a FluentAssertions plugin for R#[4][5], but it has a limited implementation (probably due to the above :-/ )

[1] https://www.jetbrains.com/help/resharper/Code_Analysis__External_Annotations.html
[2] %LOCALAPPDATA%\JetBrains\plugins\JetBrains.ExternalAnnotations.10.2.71\DotFiles\ExternalAnnotations\VisualStudio
[3] https://www.jetbrains.com/help/resharper/Contract_Annotations.html
[4] https://plugins.jetbrains.com/plugin/11879-fluentassertions-external-annotations/
[5] https://github.com/atzimler/ReSharperAnnotations

**Comment by pdavis86** [comment]
It's a work-around, but I have used an extension method so the code at least looks like it is using Fluent Assertions:

```
public static ShouldNotBeNull(this object anObject)
{
    Assert.IsNotNull(anObject);
}
```

Perhaps Fluent Assertions could add something like this?

**Comment by mu88** [comment]
@pdavis86 And where is the `Assert` class from?

But the idea could be interesting, because something like this might work:
```c#
public static void ShouldNotBeNull([NotNull] this object? o) => o.Should().NotBeNull();
```
I didn't test it, but maybe it is worth a try 🤔

**Comment by pdavis86** [comment]
> And where is the `Assert` class from?

In my case it is from NUnit but I suspect the one from MSTest will work too

**Comment by dennisdoomen** [comment]
That's isn't really helping either. But I've just reached out to Jetbrains to ask them if there is a better way.

**Comment by dennisdoomen** [comment]
Yes, and there isn't.

**Comment by dennisdoomen** [comment]
This should be solved (kind of) when #2380 is merged.

**Comment by mu88** [comment]
Thx @dennisdoomen for the update! Do I understand correctly that the following code will still show the nullable warning for `car.HasEngine` that `car` might be `null`?
```c#
var car = new Car();
car.ShouldNotBeNull();
car.HasEngine.Should().BeTrue();
```

**Comment by jotabe-net** [comment]
Copying my own comment posted in JetBrains issue https://youtrack.jetbrains.com/issue/RSRP-442740

> There is a clear explanation on why this could not be a good idea: [Workaround for ReSharper regarding `ShouldNotBeNull()` · Issue #1074 · fluentassertions/fluentassertions](https://github.com/fluentassertions/fluentassertions/issues/1074)
FluentAssertion has the concept of assertion scope, which is a code blocks that runs all assertions, even if some of them fail, and reports the results of all the assertions.
Using R# external annotations there is no way to distinguish if the "should not be null" assertion is inside a scope or not. So, if the "should not be null" assertion fails inside a scope, you can get a null reference exception, and break the expected behavior of the scope and get an ugly "null reference exception" breaking your test execution, instead of a list of "should" assertion results

>
>What I will do:
>- if the "should not be null" assertion is inside an assertion scope, I will take care of handling the null case, as the "should not be null" won't stop the execution. Of course, if I'm using a scope, I know what it is, and I know that R# inspection is right.
>- if the "should not be null" assertion is not inside a scope, I will use the classical "Assert.IsNotNull()" which will behave as if it was a "should not be null", and R# will understand that in the next lines the asserted item is not null.

>
>In the included link, I saw some people proposing to use some fake "ShouldNotBeNull" extensions, replacing the original one, but that's a very bad idea, because it would break the expected behavior inside an assertion scope.

>
>The most ideal solution would be that JetBrains handled this case by checking the existence of the scope, but that's not something that can be easily solved with external annotations.
