### ISSUE TITLE
When because message contains “{someText}”, then exception will thrown

### ISSUE THREAD

**Issue by FiresShadow** [fluentassertions/fluentassertions#551]
Example:

public void Foo(string info)
{
    object someObject = null;
    someObject.Should().BeNull($“because {info}”);
}

public void Bar()
{
    //this will throw exception:
    Foo(“{a}”);
}

**Comment by dennisdoomen** [comment]
Should be fixed in 4.19.4.

**Comment by krajek** [comment]
I retried it, and the problem still exists.
The exception thrown is 
`System.FormatException: 'Input string was not in a correct format.'`

You can assign me to the issue, I will fix it.

**Comment by dennisdoomen** [comment]
Hmm, my changes in #705 might actually fix that.

**Comment by dennisdoomen** [comment]
Scratch that. It doesn't.
